apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibmcloud-event-exporter-sa
  namespace: ibm-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibmcloud-event-exporter-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: ibmcloud-event-exporter-sa
  namespace: ibm-system
---
apiVersion: v1
data:
  cluster-config.json: |
    {
      "account_id": "",
      "cluster_id": "",
      "cluster_name": "",
      "datacenter": ""
    }
kind: ConfigMap
metadata:
  name: ibmcloud-event-exporter-config
  namespace: ibm-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ibmcloud-event-exporter
  name: ibmcloud-event-exporter-deployment
  namespace: ibm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibmcloud-event-exporter
      release: ibmcloud-event-exporter
  template:
    metadata:
      labels:
        app: ibmcloud-event-exporter
        release: ibmcloud-event-exporter
      namespace: ibm-system
    spec:
      containers:
      - args:
        - -sink-provider
        - IBM
        command:
        - /event-exporter
        env:
        - name: ACTIVITY_TRACKER_LOG_ROOT
          value: /var/log/at
        - name: SERVICE_PROVIDER_NAME
          value: ibmcloud-event-exporter
        - name: CADF_ENABLED
          value: "false"
        envFrom:
        - configMapRef:
            name: ibmcloud-event-exporter-config
        image: registry.bluemix.net/ibm/ibmcloud-event-exporter:latest
        name: ibmcloud-event-exporter
        resources:
          requests:
            memory: 100Mi
        volumeMounts:
        - mountPath: /var/log/at
          name: at-volume
      serviceAccount: ibmcloud-event-exporter-sa
      imagePullSecrets:
      - name: bluemix-default-secret-international
      serviceAccountName: ibmcloud-event-exporter-sa
      volumes:
      - emptyDir: {}
        name: at-volume
